# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

name: charmed-hpc-benchmarks tests
on:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  inclusive-naming-check:
    name: Inclusive naming check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        uses: get-woke/woke-action@v0
        with:
          fail-on-error: true

  commitlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install commitlint
        run: npm install -D @commitlint/cli @commitlint/config-conventional
      - name: Validate PR commits with commitlint
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install `just`
        run: sudo snap install just --classic
      - name: Install `uv`
        run: sudo snap install astral-uv --classic
      - name: Run linters
        run: just lint

  fmt:
    name: Format
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install `just`
        run: sudo snap install just --classic
      - name: Install `uv`
        run: sudo snap install astral-uv --classic
      - name: Run formatting
        run: just fmt
